### ISSUE TITLE
 printing problem

### ISSUE THREAD

**Issue by gilaroni** [arXiv/html_feedback#2106]
### Description

it shows "wherex_i in ..." instead of "where x_i in ..."

### (Required) What is this issue most closely related to? Select one.

Choose One

### Internal issue ID

2dc0a10c-864c-4620-bdbc-248c966085a4

### Paper URL

https://arxiv.org/html/2409.05746v1

### Browser

Chrome/128.0.0.0

### Device Type

Android

**Comment by dginev** [comment]
@gilaroni this is identical in the PDF version in the article. Could you please reach out to the author directly for a correction?

For now this is within expected behavior on the HTML side.

![Screenshot from 2024-09-13 16-21-18](https://github.com/user-attachments/assets/b46a2f17-3394-431c-82ec-9bf223fc3da3)
