### ISSUE TITLE
 Text is highlighted strangely

### ISSUE THREAD

**Issue by wandadars** [arXiv/html_feedback#2171]
### Description

At a random point in the article, a purple-like highlighting starts and continues down the document.

The article is: **https://arxiv.org/html/2404.04326v1#:~:text=1.,corresponding%20examples%20of%20the%20hypotheses.&text=2.,example%20in%20a%20second%20prompt.**

### (Optional:) Please add any files, screenshots, or other information here.

![Screenshot from 2024-09-23 14-43-39](https://github.com/user-attachments/assets/f46fb6da-17f5-4d75-a7ee-bd794f50df24)

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

847c3bc9-e3fc-4374-987d-4242fa8fd7b7

### Paper URL

https://arxiv.org/html/2404.04326v1

### Browser

Chrome/129.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Hi @wandadars ,

Where did you obtain that link from? 

It has a `#:~:text=` [text fragment](https://developer.mozilla.org/en-US/docs/Web/URI/Fragment/Text_fragments) included in it. If you remove the trailing part after the `#` character the highlight will disappear.

Chrome has a right-click feature "Copy link to highlight" which creates such URLs. The purple color is the current choice for stylizing these in dark mode I believe.

I'll close here, since this looks "as intended" to me.

**Comment by wandadars** [comment]
It was linked from Google. I guess it was the quick-answer section at the top that performed the highlighting.

I searched for "llm as a way to generate hypotheses" in Google and the Arxiv link was at the top.

**Comment by dginev** [comment]
Indeed, Google search sometimes adds highlights to direct the attention of the reader. 

Thank you for the extra information!
